# Generated by Django 4.1.2 on 2022-11-06 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='Emprestimo',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='livro',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='categoria',
        ),
    ]
