# Generated by Django 4.1.2 on 2022-11-07 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_aluno_emprestimo_remove_curso_aluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='Emprestimo',
            field=models.ManyToManyField(blank=True, null=True, to='main.emprestimo'),
        ),
        migrations.AddField(
            model_name='curso',
            name='aluno',
            field=models.ManyToManyField(blank=True, null=True, to='main.aluno'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.livro'),
        ),
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.autor'),
        ),
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.categoria'),
        ),
    ]
