# Generated by Django 4.1 on 2022-11-17 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aluno_emprestimo_curso_aluno_emprestimo_livro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='Emprestimo',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.aluno'),
        ),
    ]
